spring.application.name=artedental-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cadi_artedental
spring.datasource.username=postgres
spring.datasource.password=kiwi26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.time-zone=America/Mexico_City

server.port=8080

agenda.reminder.scheduler-delay-ms=60000

whatsapp.api.base-url=https://graph.facebook.com
whatsapp.api.version=v23.0

whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}

whatsapp.template-name=hello_world
whatsapp.template-language=en_US

app.clinic-name=Arte Dental